### ISSUE TITLE
`startDiscovery`と`stopDiscovery`を定期的に実行するとErrorが発生する

### ISSUE THREAD

**Issue by youkinjoh** [futomi/node-onvif#1]
```
setInterval(function() {
  var onvif = require('node-onvif');
  onvif.startDiscovery(function(info) {
    var xaddr = info.xaddrs[0];
    var device = new onvif.OnvifDevice({
      xaddr: xaddr
    });
    device.init(function(error) {
      if(error) {
        console.log('[ERROR] ' + error.message);
      } else {
        console.log(device.address);
      }
    });
    setTimeout(function() {onvif.stopDiscovery();}, 3000);
  });
},5000);
```
上記コードを実行すると、数回はアドレスを取得するのですが、
2~3回繰り返すと以下のようなエラーで異常終了します。
```
dgram.js:520
    throw new Error('Not running'); // error message from dgram_legacy.js
    ^

Error: Not running
    at Socket._healthCheck (dgram.js:520:11)
    at Socket.close (dgram.js:414:8)
    at Onvif.stopDiscovery ([proj dir]/node_modules/node-onvif/lib/node-onvif.js:160:12)
    at Timeout._onTimeout ([proj dir]/index.js:15:34)
    at tryOnTimeout (timers.js:228:11)
    at Timer.listOnTimeout (timers.js:202:5)
```

**Comment by youkinjoh** [comment]
先程のコードが冗長だったため以下のコードで確認してみましたが同じ結果でした。
```
setInterval(function() {
  var onvif = require('node-onvif');
  onvif.startDiscovery(function(info) {
    var xaddr = info.xaddrs[0];
    console.log(xaddr);
    setTimeout(function() {onvif.stopDiscovery();}, 3000);
  });
},5000);
```

**Comment by youkinjoh** [comment]
`startDiscovery`は見つかった端末の数呼ばれるんですね。失礼しました。
`stopDiscovery `が必要以上にcallされていたのが原因でした。
closeします。
