### ISSUE TITLE
Failed to initialize the device

### ISSUE THREAD

**Issue by AngThomas** [futomi/node-onvif#22]
Hello,

I got this:
`Failed to initialize the device: Error: Networ Error: socket hang up at services.media.getProfiles (node_modules\node-onvif\lib\modules\device.js:464:12)
 at promise.then.catch (node_modules\node-onvif\lib\modules\service-media.js:392:4)
at<anonymous>`

I try to launch example of Create OnvifDevice object:

'const onvif = require('node-onvif');
// Create an OnvifDevice object
let device = new onvif.OnvifDevice({
  xaddr: 'http://IP:PORT/onvif/device_service',
  user : 'xxxx',
  pass : 'xxxx'
});

// Initialize the OnvifDevice object
device.init().then((info) => {
  // Show the detailed information of the device.
  console.log(JSON.stringify(info, null, '  '));
}).catch((error) => {
  console.error(error);
});'

It gives me this error when I try to launch it on Windows Server 2012, but when I launch it on my pc (Win 10), it works fine. I tried to turn off firewall, make in and outbound rules, with no success. 
Any help is appreciated.

**Comment by futomi** [comment]
I've not find the reason yet. I updated the `node-onvif` today. Though I'm not sure this issue is solved, try the latest version of the `node-onvif`.

**Comment by mishitpatel** [comment]
@futomi I am able to discover the device properly but not able to connect it. It throws below error 
```
Error: Failed to initialize the device: Error: 400 Bad Request - Sender not authorized
    at services.device.getCapabilities (/Users/Mishi/kiwi/repo/camera/node_modules/node-onvif/lib/modules/device.js:392:12)
    at promise.then.catch (/Users/Mishi/kiwi/repo/camera/node_modules/node-onvif/lib/modules/service-device.js:120:4)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```
I have verified that username and password is correct. I am able to invoke ONVIF api through SOAP client with same username and password. I am using AXIS camera. Any idea what would be wrong ? Thanks in advance.

**Comment by davidgatti** [comment]
@futomi The issue is how your code authenticates to the camera. You should send the authentication in the header. You instead pass the user name and password in the body. It seams that you have this feature in `http-auth.js` but are using this module only in the .fetchSnapshot() function. 

Is there a reason why you do it this way?

**Comment by futomi** [comment]
@davidgatti Thank you for your advice. I'll try to check the code this weekend.

**Comment by TutorJoes-Stanley** [comment]
Error: Failed to initialize the device: Error: 400 Bad Request - Sender not Authorized
    at services.device.getDeviceInformation (C:\Users\tutor\Desktop\RTSP-STREAM\node_modules\node-onvif\lib\modules\device.js:453:12)
    at promise.then.catch (C:\Users\tutor\Desktop\RTSP-STREAM\node_modules\node-onvif\lib\modules\service-device.js:853:4)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by TutorJoes-Stanley** [comment]
I have same problem can any one help me

**Comment by neonmura** [comment]
> Error: Failed to initialize the device: Error: 400 Bad Request - Sender not Authorized
> at services.device.getDeviceInformation (C:\Users\tutor\Desktop\RTSP-STREAM\node_modules\node-onvif\lib\modules\device.js:453:12)
> at promise.then.catch (C:\Users\tutor\Desktop\RTSP-STREAM\node_modules\node-onvif\lib\modules\service-device.js:853:4)
> at process._tickCallback (internal/process/next_tick.js:68:7)

Normally this happens when the clock in your client and camera differs more than 5 secs. I've noticed that in my camera, and solved it by either syncing both camera and client to same NTP or disable the function of "replay attack protection" in the axis camera.

**Comment by zainiazhr14** [comment]
its because user not have permission for access

**Comment by bradjin8** [comment]
`
Error: Failed to initialize the device: Error: 400 Bad Request - Sender not authorized
    at /Volumes/DATA/Web/Onvif/node_modules/node-onvif/lib/modules/device.js:396:12
    at /Volumes/DATA/Web/Onvif/node_modules/node-onvif/lib/modules/service-device.js:120:4
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
`
It has still the same issue.
@futomi

**Comment by yashrajsapra** [comment]
Hi,
Even I'm facing the same issue, I'm able to list all the cameras, but while initializing it's failing

'Failed to initialize the device: Error: 400 Bad Request - Sender not authorized'
