### ISSUE TITLE
fetchSnapshot socket hang up error

### ISSUE THREAD

**Issue by aldopa** [futomi/node-onvif#36]
Hi,
i'm testing node-onvif with a Vitorcam CA-31.

All works properly (discovery, get profile, change profile, get info ...) but fetchSnapshot fails with 

{ Error: socket hang up
    at createHangUpError (_http_client.js:331:15)
    at Socket.socketOnEnd (_http_client.js:423:23)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9) code: 'ECONNRESET' }

it seems as cam close connection, what's happening ?

**Comment by Gruid** [comment]
Hi all,
I found an issue probably about implemetation of the onvif standard. Probably on side of my camera. Anyway this is in my case reason of the same error - socket hang up error.

My Hikvision camera - _**DS-2CD2042WD-I**_ needs this snapshot URL:
http://160.218.111.47:5201//onvif-http/snapshot?
But after initiation I get this address without question mark:
http://160.218.111.47:5201//onvif-http/snapshot

I made this update in file device.js - row 188
`path: ourl.path+'?',`

And snapshot works fine for this camera.
Maybe can help ;)

PS: PTZ and another function didn't tested yet with this type.

**Comment by Patrick2402** [comment]
Hi! 
Does anybody find the solution of above case? I am using HikVision cammera and node-onvif module... and I get the same error what @aldopa....
