### ISSUE TITLE
Error: Cannot find module 'node-onvif'

### ISSUE THREAD

**Issue by 3PO** [futomi/node-onvif#45]
Hi, 
when i execute node, i get the following issue:

    server01 ~ # node /tmp/node-onvif/sample/manager/server.js
    module.js:550
        throw err;
        ^
    
    Error: Cannot find module 'node-onvif'
        at Function.Module._resolveFilename (module.js:548:15)
        at Function.Module._load (module.js:475:25)
        at Module.require (module.js:597:17)
        at require (internal/module.js:11:18)
        at Object.<anonymous> (/tmp/node-onvif/sample/manager/server.js:8:10)
        at Module._compile (module.js:653:30)
        at Object.Module._extensions..js (module.js:664:10)
        at Module.load (module.js:566:32)
        at tryModuleLoad (module.js:506:12)
        at Function.Module._load (module.js:498:3)
    server01 ~ # 

node-onfiv is installed:

    server01 ~ # npm list
    node-onvif@0.1.7 /root
    ├─┬ html@1.0.0
    │ └─┬ concat-stream@1.6.2
    │   ├── buffer-from@1.1.1
    │   ├── inherits@2.0.3
    │   ├─┬ readable-stream@2.3.6
    │   │ ├── core-util-is@1.0.2
    │   │ ├── inherits@2.0.3 deduped
    │   │ ├── isarray@1.0.0
    │   │ ├── process-nextick-args@2.0.0
    │   │ ├── safe-buffer@5.1.2
    │   │ ├─┬ string_decoder@1.1.1
    │   │ │ └── safe-buffer@5.1.2 deduped
    │   │ └── util-deprecate@1.0.2
    │   └── typedarray@0.0.6
    └─┬ xml2js@0.4.19
      ├── sax@1.2.4
      └── xmlbuilder@9.0.7
    
    server01 ~ #

Where is my fail?

**Comment by futomi** [comment]
Try to change the current directory as follows:

```
$ cd /tmp/node-onvif/sample/manager
$ node ./server.js
```

Did you run the script as root? You should run the script as normal user.

**Comment by 3PO** [comment]
Same issue:

    server01 ~ # cd /tmp/node-onvif/sample/manager
    server01 manager # node ./server.js
    module.js:550
        throw err;
        ^
    
    Error: Cannot find module 'node-onvif'
        at Function.Module._resolveFilename (module.js:548:15)
        at Function.Module._load (module.js:475:25)
        at Module.require (module.js:597:17)
        at require (internal/module.js:11:18)
        at Object.<anonymous> (/tmp/node-onvif/sample/manager/server.js:8:10)
        at Module._compile (module.js:653:30)
        at Object.Module._extensions..js (module.js:664:10)
        at Module.load (module.js:566:32)
        at tryModuleLoad (module.js:506:12)
        at Function.Module._load (module.js:498:3)
    server01 manager #
Yes, the script is running as root.
This is a server, the are no other users.

**Comment by futomi** [comment]
I think that the module path is not resolved properly in your environment.
Anyway, the node-onvif works without being installed using `npm`.
Copy the `node-onvif` directory in the `/tmp`. Note that you must copy all files.
Then, do as follows:

```
# cd /tmp/node-onvif/sample/manager
# node ./server.js
```

**Comment by 3PO** [comment]
Is seems, it is working only in the User $HOMEDIR.

The following is working:

```
server01 manager # cd ~
server01 ~ # npm install -s node-onvif
server01 ~ # git clone https://github.com/futomi/node-onvif
Klone nach 'node-onvif' ...
remote: Enumerating objects: 232, done.
remote: Total 232 (delta 0), reused 0 (delta 0), pack-reused 232
Empfange Objekte: 100% (232/232), 209.57 KiB | 597.00 KiB/s, Fertig.
Löse Unterschiede auf: 100% (124/124), Fertig.
server01 ~ # cd node-onvif/sample/manager
server01 manager # node ./server.js
module.js:550
    throw err;
    ^

Error: Cannot find module 'websocket'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/root/node-onvif/sample/manager/server.js:10:23)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
server01 manager # cd
server01 ~ # npm install -s websocket
make: Verzeichnis „/root/node_modules/websocket/build“ wird betreten
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  COPY Release/bufferutil.node
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/obj.target/validation.node
  COPY Release/validation.node
make: Verzeichnis „/root/node_modules/websocket/build“ wird verlassen
+ websocket@1.0.28
added 7 packages from 15 contributors and audited 24 packages in 2.851s
found 0 vulnerabilities

server01 ~ # cd node-onvif/sample/manager
server01 manager # node ./server.js
Listening on port 8880


```
