### ISSUE TITLE
The action requested requires authorization

### ISSUE THREAD

**Issue by strarsis** [futomi/node-onvif#60]
Despite using correct URL and credentials (username + password), the connection to IPCam fails:
````
Error: Failed to initialize the device: Error: 400 Bad Request - The action requested requires authorization and the sender is not authorized
    at services.device.getDeviceInformation ([...]/node_modules/node-onvif/lib/modules/device.js:453:12)
    at promise.then.catch ([...]/node_modules/node-onvif/lib/modules/service-device.js:853:4)
    at process._tickCallback (internal/process/next_tick.js:68:7)
````

**Comment by strarsis** [comment]
My mistake, I used wrong credentials without noticing it.

**Comment by bradjin8** [comment]
I set the credentials correctly, but get the same error.
