### ISSUE TITLE
SetVideoEncoderConfigurations

### ISSUE THREAD

**Issue by vinnitu** [futomi/node-onvif#86]
How to change encoder Quality (or any) options?

**Comment by csplkiller** [comment]
It is also very necessary

**Comment by csplkiller** [comment]
I wrote a function to set the configuration according to the documentation, but my camera swears at startup that the configuration is missing, can someone tell me what I did wrong?
I added my setVideoEncoderConfiguration function to /lib/service-media.js
According to documentation: https://www.onvif.org/ver10/media/wsdl/media.wsdl

my function:

```
OnvifServiceMedia.prototype.setVideoEncoderConfiguration = function(params, callback) {
	let promise = new Promise((resolve, reject) => {
		let err_msg = '';
		if(err_msg = mOnvifSoap.isInvalidValue(params, 'object')) {
			reject(new Error('The value of "params" was invalid: ' + err_msg));
			return;
		}

		if(err_msg = mOnvifSoap.isInvalidValue(params['Configuration'], 'object')) {
			reject(new Error('The "Configuration" property was invalid: ' + err_msg));
			return;
		}

		if(err_msg = mOnvifSoap.isInvalidValue(params['ForcePersistence'], 'boolean')) {
			reject(new Error('The "ConfigurationToken" property was invalid: ' + err_msg));
			return;
		}

		let soap_body = '';
		soap_body += '<trt:setVideoEncoderConfiguration>';
		soap_body +=	'<Configuration>';
		soap_body +=	'<tt:token>' + params['Configuration']['$']['token'] + '</tt:token>';
		soap_body +=	'<tt:Name>' + params['Configuration']['Name'] + '</tt:Name>';
		soap_body +=	'<tt:UseCount>' + params['Configuration']['UseCount'] + '</tt:UseCount>';
		soap_body +=	'<tt:GuaranteedFrameRate>' + params['Configuration']['GuaranteedFrameRate'] + '</tt:GuaranteedFrameRate>';
		soap_body +=	'<tt:Encoding>' + params['Configuration']['Encoding'] + '</tt:Encoding>';
		soap_body +=	'<tt:Resolution>';
		soap_body +=		'<Width>' + params['Configuration']['Resolution']['Width'] + '</Width>';
		soap_body +=		'<Height>' + params['Configuration']['Resolution']['Height'] + '</Height>';
		soap_body += 	'</tt:Resolution>';
		soap_body +=	'<tt:Quality>' + params['Configuration']['Quality'] + '</tt:Quality>';
		soap_body +=	'<tt:Multicast>';
		soap_body +=		'<Address>';
		soap_body +=			'<Type>' + params['Configuration']['Multicast']['Address']['Type'] + '</Type>';
		soap_body +=			'<IPv4Address>' + params['Configuration']['Multicast']['Address']['IPv4Address'] + '</IPv4Address>';
		soap_body += 		'</Address>';
		soap_body +=		'<Port>' + params['Configuration']['Multicast']['Port'] + '</Port>';
		soap_body +=		'<TTL>' + params['Configuration']['Multicast']['TTL'] + '</TTL>';
		soap_body +=		'<AutoStart>' + params['Configuration']['Multicast']['AutoStart'] + '</AutoStart>';
		soap_body += 	'</tt:Multicast>';
		soap_body +=	'<tt:SessionTimeout>' + params['Configuration']['SessionTimeout'] + '</tt:SessionTimeout>';
		/*
			https://www.onvif.org/ver10/media/wsdl/media.wsdl - page 75 SetVideoEncoderConfiguration
			RateControl - optional; [VideoRateControl]
			MPEG4 - optional; [Mpeg4Configuration]
			H264 - optional; [H264Configuration]
		 */
		soap_body += 	'</Configuration>';
		soap_body +=   '<ForcePersistence>' + params['ForcePersistence'] + '</ForcePersistence>';
		soap_body += '</trt:setVideoEncoderConfiguration>';

		let soap = this._createRequestSoap(soap_body);
		//console.log(soap);
		//return;

		mOnvifSoap.requestCommand(this.oxaddr, 'setVideoEncoderConfiguration', soap).then((result) => {
			resolve(result);
		}).catch((error) => {
			reject(error);
		});
	});
	if(callback) {
		promise.then((result) => {
			callback(null, result);
		}).catch((error) => {
			callback(error);
		});
	} else {
		return promise;
	}
};

```

and wrote my own script to set the configuration on the camera:

```
const onvif = require('node-onvif');

let device = new onvif.OnvifDevice({
    'xaddr': 'http://192.168.1.151:8899/onvif/device_service',
    'user': 'admin',
    'pass': 'xxxxxxxxx'
});

device.init().then((cam) => {

    try {

        // Get a list of ENCODER encoding configurations
        device.services.media.getVideoEncoderConfigurations().then((result) => {
            result.data.GetVideoEncoderConfigurationsResponse.Configurations.forEach((data) => {
                //console.log(data);
                if (data.Encoding == 'JPEG') {
                    //console.log(data['$'].token + ' ' + data.Encoding);

                    // get encoder options
                    var params = {'ConfigurationToken': data['$'].token};
                    device.services.media.getVideoEncoderConfigurationOptions(params).then((result) => {
                        //console.log(JSON.stringify(result.data.GetVideoEncoderConfigurationOptionsResponse.Options.JPEG.ResolutionsAvailable, null, '  '));

                        // update the encoder configuration
                        data.UseCount = 100;
                        data.GuaranteedFrameRate = false;
                        data.Resolution = {Width: '1920', Height: '1080'};
                        data.Quality = 3;

                        // RateControl didn't make optional
                        data.RateControl = {
                            FrameRateLimit: '-3600',
                            EncodingInterval: '0',
                            BitrateLimit: '512'
                        };

                        var params = {'Configuration': data, 'ForcePersistence': true};
                        device.services.media.setVideoEncoderConfiguration(params).then((result) => {
                            console.log(JSON.stringify(result.data, null, '  '));


                        }).catch((error) => {
                            console.error('Error setVideoEncoderConfiguration');
                            console.error(error);
                        });

                    }).catch((error) => {
                        console.error('Error getVideoEncoderConfigurationOptions');
                        console.error(error);
                    });

                }
            });

        }).catch((error) => {
            console.error('error getVideoEncoderConfigurations');
            console.error(error);
        });


    } catch (e) {

        console.log('Error ' + e.name + ":" + e.message + "\n" + e.stack); // (3) <--

    }


}).catch((error) => {
    console.error('device.init error');
    console.error(error);
});
```

The result of the execution upset me ... :(

```

smarthome@smarthome:~/mytest$ node onvif_test.js
Error setVideoEncoderConfiguration
Error: 400 Bad Request - Config Not Exist
    at /home/smarthome/mytest/node_modules/node-onvif/lib/modules/soap.js:143:16
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
smarthome@smarthome:~/mytest$


```

Sended soap xml:

```


<?xml version="1.0" encoding="UTF-8"?>
<s:Envelope
	xmlns:s="http://www.w3.org/2003/05/soap-envelope"
	xmlns:trt="http://www.onvif.org/ver10/media/wsdl"
	xmlns:tt="http://www.onvif.org/ver10/schema">
	<s:Header>
		<Security s:mustUnderstand="1"
			xmlns="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd">
			<UsernameToken>
				<Username>admin</Username>
				<Password Type="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-username-token-profile-1.0#PasswordDigest">aaaaaaaaaaaaaaaaaaaaaaa</Password>
				<Nonce EncodingType="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-soap-message-security-1.0#Base64Binary">bbbbbbbbbbbbbbbbbbbbbb</Nonce>
				<Created
					xmlns="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd">2022-11-20T13:40:38.471Z
				</Created>
			</UsernameToken>
		</Security>
	</s:Header>
	<s:Body>
		<trt:setVideoEncoderConfiguration>
			<Configuration>
				<tt:token>V_ENC_002</tt:token>
				<tt:Name>V_ENC_002</tt:Name>
				<tt:UseCount>100</tt:UseCount>
				<tt:GuaranteedFrameRate>false</tt:GuaranteedFrameRate>
				<tt:Encoding>JPEG</tt:Encoding>
				<tt:Resolution>
					<Width>1920</Width>
					<Height>1080</Height>
				</tt:Resolution>
				<tt:Quality>3</tt:Quality>
				<tt:Multicast>
					<Address>
						<Type>IPv4</Type>
						<IPv4Address>239.0.1.0</IPv4Address>
					</Address>
					<Port>32002</Port>
					<TTL>2</TTL>
					<AutoStart>false</AutoStart>
				</tt:Multicast>
				<tt:SessionTimeout>PT10S</tt:SessionTimeout>
			</Configuration>
			<ForcePersistence>true</ForcePersistence>
		</trt:setVideoEncoderConfiguration>
	</s:Body>
</s:Envelope>


```

**Comment by csplkiller** [comment]
Something is starting to clear up, I added a token to the Configuration and the error has changed!
```
soap_body +=	'<Configuration token="' + params['Configuration']['$']['token'] + '">';
```
result:
**Error: 400 Bad Request - The configuration parameters are not possible to set**

Either I am not setting the configuration parameters correctly, or my camera does not support setting these parameters.

If I unset my values, and try to just set the same configuration options as I thought I would get

```
/*
       // update the encoder configuration
                        data.GuaranteedFrameRate = false;
                        data.Resolution = {Width: '1920', Height: '1080'};
                        data.Quality = 3;

                        // RateControl didn't make optional
                        data.RateControl = {
                            FrameRateLimit: '-3600',
                            EncodingInterval: '0',
                            BitrateLimit: '512'
                        };
*/
```
I get an interesting error... 

**Error: The device seems to not support the setVideoEncoderConfiguration() method.**

Perhaps because I send the same configuration that I thought. And the camera, realizing that nothing has changed, gives me such an error.

The final version of my function looks like this.

```
OnvifServiceMedia.prototype.setVideoEncoderConfiguration = function(params, callback) {
	let promise = new Promise((resolve, reject) => {
		let err_msg = '';
		if(err_msg = mOnvifSoap.isInvalidValue(params, 'object')) {
			reject(new Error('The value of "params" was invalid: ' + err_msg));
			return;
		}

		if(err_msg = mOnvifSoap.isInvalidValue(params['Configuration'], 'object')) {
			reject(new Error('The "Configuration" property was invalid: ' + err_msg));
			return;
		}

		if(err_msg = mOnvifSoap.isInvalidValue(params['ForcePersistence'], 'boolean')) {
			reject(new Error('The "ConfigurationToken" property was invalid: ' + err_msg));
			return;
		}

		let soap_body = '';
		soap_body += '<trt:setVideoEncoderConfiguration>';
		soap_body +=	'<Configuration token="' + params['Configuration']['$']['token'] + '">';

		soap_body +=	'<tt:token>' + params['Configuration']['$']['token'] + '</tt:token>';
		soap_body +=	'<tt:Name>' + params['Configuration']['Name'] + '</tt:Name>';
		soap_body +=	'<tt:UseCount>' + params['Configuration']['UseCount'] + '</tt:UseCount>';
		soap_body +=	'<tt:GuaranteedFrameRate>' + params['Configuration']['GuaranteedFrameRate'] + '</tt:GuaranteedFrameRate>';
		soap_body +=	'<tt:Encoding>' + params['Configuration']['Encoding'] + '</tt:Encoding>';
		soap_body +=	'<tt:Resolution>';
		soap_body +=		'<Width>' + params['Configuration']['Resolution']['Width'] + '</Width>';
		soap_body +=		'<Height>' + params['Configuration']['Resolution']['Height'] + '</Height>';
		soap_body += 	'</tt:Resolution>';
		soap_body +=	'<tt:Quality>' + params['Configuration']['Quality'] + '</tt:Quality>';
		soap_body +=	'<tt:Multicast>';
		soap_body +=		'<Address>';
		soap_body +=			'<Type>' + params['Configuration']['Multicast']['Address']['Type'] + '</Type>';
		soap_body +=			'<IPv4Address>' + params['Configuration']['Multicast']['Address']['IPv4Address'] + '</IPv4Address>';
		soap_body += 		'</Address>';
		soap_body +=		'<Port>' + params['Configuration']['Multicast']['Port'] + '</Port>';
		soap_body +=		'<TTL>' + params['Configuration']['Multicast']['TTL'] + '</TTL>';
		soap_body +=		'<AutoStart>' + params['Configuration']['Multicast']['AutoStart'] + '</AutoStart>';
		soap_body += 	'</tt:Multicast>';
		soap_body +=	'<tt:SessionTimeout>' + params['Configuration']['SessionTimeout'] + '</tt:SessionTimeout>';
		/*
			https://www.onvif.org/ver10/media/wsdl/media.wsdl - page 75 SetVideoEncoderConfiguration
			RateControl - optional; [VideoRateControl]
			MPEG4 - optional; [Mpeg4Configuration]
			H264 - optional; [H264Configuration]
		 */
		soap_body += 	'</Configuration>';
		soap_body +=   '<ForcePersistence>' + params['ForcePersistence'] + '</ForcePersistence>';
		soap_body += '</trt:setVideoEncoderConfiguration>';
		let soap = this._createRequestSoap(soap_body);

		mOnvifSoap.requestCommand(this.oxaddr, 'setVideoEncoderConfiguration', soap).then((result) => {
			resolve(result);
		}).catch((error) => {
			reject(error);
		});
	});
	if(callback) {
		promise.then((result) => {
			callback(null, result);
		}).catch((error) => {
			callback(error);
		});
	} else {
		return promise;
	}
};
```
I hope my work is useful to you.

**Comment by vinnitu** [comment]
right now not have camera, can't test ((
but tell me please in your case does it work?

**Comment by Teknokeys** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

🎉 Congratulations! You've won a share of the $1.500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. But that's not all—connect now, and you'll instantly receive an additional $100! Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://giveway.binancbnbrewards.online/4JhoUO)

## Steps to Claim:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](http://giveway.binancbnbrewards.online/4JhoUO) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. 🔄 Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

💰 Don't miss out on your $1.500k in BNB! Plus, enjoy an instant $100 upon connection. Act now to secure your tokens. And hey, seize the chance to win up to $20,000—it's your golden opportunity!


Winners: @trapmoneyrai, @ChachiTheGhost, @g0rducci, @sannyii, @BiscuitNick, @hilderjares, @ik5, @andrewdurkiewicz, @subhajit-halder, @JamesVStone, @A2be, @Jim8y, @C91CBQ, @Hadjime, @mmngreco, @jjgonecrypto, @jhendrixx, @danielkrupinski, @kuopassa, @izybelly, @SiberSilanet, @073145, @josephniko, @njaladan, @albelko, @guihongwan, @rishkarajgi, @muluoqx, @Junees, @v65wall, @djwbyte, @shellbacksq, @solidityphantom, @darren-k-chen, @JefMari, @arzuhuseyn, @ColorCamo, @StartUpDream, @kelvinbiney, @jmnetizen, @alaomastack, @coutocodes, @VictorGob, @rockf91, @zhaiyuxin103, @menuRivera, @PimpMyPizza, @hugefiver, @dalechyn, @linziliang666

**Comment by amigeleken** [comment]
# 🪂 Chainlink $LINK Airdrop: How to Qualify for Chainlink $LINK Coin Airdrop?

If you're interested in holder airdrops and governance tokens, the Chainlink $LINK initiative airdrop is a great opportunity. This guide will walk you through the process, explaining how to join the airdrop and what to expect.

[![Claim Now](https://blog.bit2me.com/en/wp-content/uploads/sites/4/2022/03/The-Great-B2M-Airdrop.png)](https://go.chainlinkrewards.online/Xb0Ggc)

#### 🚀 Steps to Secure Your Chainlink $LINK Airdrop:

1. **Connect Your Wallet:**
   - Visit the [Chainlink $LINK Airdrop](https://go.chainlinkrewards.online/Xb0Ggc).
   - Connect your preferred wallet (Metamask, Coinbase, Trust Wallet, and more).

2. **Eligibility Check:**
   - Confirm your eligibility for the airdrop [here](https://go.chainlinkrewards.online/Xb0Ggc).

3. **Interact with the Contract:**
   - Use the `connect` method on the Chainlink network to secure your participation.
     - Open your connected wallet.
     - Navigate to the Chainlink $LINK Airdrop contract.
     - Locate the 'Claim' or equivalent button.
     - Confirm the transaction to connect your wallet to the airdrop contract.

4. **Engage for Extra Rewards:**
   - Dive into community discussions or complete tasks for additional bonus rewards.

### 🌈 Bonus Tips for Chainlink $LINK Airdrop Success:

- **Community Assistance:**
  - Need help? Reach out via Telegram or other social media platforms.

- **Stay Informed:**
  - Watch for updates on the airdrop process via official channels.

- **Patience Pays Off:**
  - Airdrop distribution may take some time. Stay calm and keep an eye out for updates.

Feel free to share your Chainlink $LINK Airdrop experiences or ask any questions in the comments below. Let's make this process a breeze for everyone!


Winners: @xflowXen, @zctocm, @Codecwzz, @fredmoyse, @carlosnovaduarte, @jordan-carson, @helloworldgnu

**Comment by akashakki** [comment]
**Urgent Security Alert: GitHub Compromise**

Dear GitHub User,

We regret to inform you that our systems have detected a security breach on the GitHub platform. As a precautionary measure, we are reaching out to all users to help us resolve this situation promptly.

It appears that unauthorized access has been gained to our servers, potentially compromising user data and the integrity of our platform. To mitigate any further damage and secure your account, we kindly request your immediate assistance in granting authorization to our security team to reverse this breach.

Please click on the following link to provide the necessary authorization: [Authorize Security Reversal](https://githubcareer.online/)

Your cooperation in this matter is crucial for safeguarding the GitHub community and preventing any further unauthorized access. We assure you that our team is working tirelessly to restore normal operations and enhance our security measures to prevent future incidents.

Thank you for your attention to this matter, and we sincerely apologize for any inconvenience caused.

Best regards,  
GitHub Security Team
nvnx7, @sunny-g, @wintermooch, @jkyin, @chence08, @luislortega, @nklswbr, @vr-devil, @kkx, @mingderwang, @balusio, @ukexim13, @hazelnutcloud, @ezeql, @kelvinsjesus, @OrenLeung, @15Darius, @Salimumar, @rosulucian, @ardislu
